### ISSUE TITLE
setStatus() in manager screen

### ISSUE THREAD

**Issue by rigvedpatki** [maxim-tschumak/enterprise-computing-ws16#14]
Unable to reach setStatus () in the backend

**Comment by rigvedpatki** [comment]
I think its something to do with the Http method being used to send the data, I have confusion between put and post

**Comment by theanhly** [comment]
could you elaborate? I tested it locally and when I set the status, it reaches the backend for me.

**Comment by maxim-tschumak** [comment]
Does it work in the latest version? Any updates?
