### ISSUE TITLE
Backend: Handle file upload, create request and send mail

### ISSUE THREAD

**Issue by maxim-tschumak** [maxim-tschumak/enterprise-computing-ws16#5]

**Comment by rigvedpatki** [comment]
Hey Guys
In EmployeeRequestController.java, for the function createRequest should I change the parameter "name"  to an Object which we can later parse to an EmplyoeeRequest instance ?

**Comment by maxim-tschumak** [comment]
Feel free to change the method's signatures, it was just an idea of how they could look like.
And you don't have to parse the objects manually. Spring Rest does it automatically (it uses Jackson to parse/generate JSON objects). Here you can find a good introduction and some links to documentation: https://spring.io/guides/gs/rest-service/
